server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.97.187.198:8081/gaea/eureka
spring:
  application:
    name: gaea-sso
  redis:
    host: 39.97.187.198
    port: 6379
    password: misterdong
ribbon:
  ReadTimeout: 10000