server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.97.187.198:8081/gaea/eureka
spring:
  application:
    name: gaea-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/erp?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    name: gaea_user
