server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.97.187.198:8081/gaea/eureka
spring:
  application:
    name: gaea-user
  datasource:
    url: jdbc:mysql://39.97.187.198:3306/gaea?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: gaea
    password: ItehSooRxuvwmlXv
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver











mybatis:
  mapper-locations: classpath:mapping/*.xml
